\@setckpt{abbrevs_en}{
\@setckpt{abstract_en}{
\@setckpt{acknows_en}{
\@setckpt{background}{
\@setckpt{intro}{
\@setckpt{validation}{
\@setckpt{workplan}{
\@writefile{lof}{\addvspace {10\p@ }}
\@writefile{lof}{\addvspace {10\p@ }}
\@writefile{lof}{\addvspace {10\p@ }}
\@writefile{lof}{\addvspace {10\p@ }}
\@writefile{lof}{\select@language{english}}
\@writefile{lot}{\addvspace {10\p@ }}
\@writefile{lot}{\addvspace {10\p@ }}
\@writefile{lot}{\addvspace {10\p@ }}
\@writefile{lot}{\addvspace {10\p@ }}
\@writefile{lot}{\select@language{english}}
\@writefile{toc}{\contentsline {chapter}{References}{9}{section*.12}}
\@writefile{toc}{\contentsline {chapter}{\numberline {1}Introduction}{1}{chapter.1}}
\@writefile{toc}{\contentsline {chapter}{\numberline {2}Background}{3}{chapter.2}}
\@writefile{toc}{\contentsline {chapter}{\numberline {3}Datasets and Validation}{5}{chapter.3}}
\@writefile{toc}{\contentsline {chapter}{\numberline {4}Work Plan}{7}{chapter.4}}
\@writefile{toc}{\contentsline {section}{\numberline {1.1}Context and Motivation}{1}{section.1.1}}
\@writefile{toc}{\contentsline {section}{\numberline {1.2}Objectives}{1}{section.1.2}}
\@writefile{toc}{\contentsline {section}{\numberline {1.3}Document Outline}{1}{section.1.3}}
\@writefile{toc}{\contentsline {section}{\numberline {2.1}Introduction}{3}{section.2.1}}
\@writefile{toc}{\contentsline {section}{\numberline {2.2}Genome Assembly}{3}{section.2.2}}
\@writefile{toc}{\contentsline {section}{\numberline {2.3}Machine Learning}{3}{section.2.3}}
\@writefile{toc}{\contentsline {section}{\numberline {3.1}Datasets}{5}{section.3.1}}
\@writefile{toc}{\contentsline {section}{\numberline {3.2}Result Validation}{5}{section.3.2}}
\@writefile{toc}{\contentsline {section}{\numberline {4.1}Development Phases}{7}{section.4.1}}
\@writefile{toc}{\contentsline {section}{\numberline {4.2}Schedule Planning}{7}{section.4.2}}
\@writefile{toc}{\select@language{english}}
\AtEndDocument{\ifx\hyper@anchor\@undefined
\HyperFirstAtBeginDocument{\ifx\hyper@anchor\@undefined
\bibdata{myrefs}
\bibstyle{alpha}
\fi}
\fi}
\gdef\HyperFirstAtBeginDocument#1{#1}
\gdef\contentsline#1#2#3#4{\oldcontentsline{#1}{#2}{#3}}
\gdef\newlabel#1#2{\newlabelxx{#1}#2}
\gdef\newlabelxx#1#2#3#4#5#6{\oldnewlabel{#1}{{#2}{#3}}}
\global\let\hyper@last\relax 
\global\let\oldcontentsline\contentsline
\global\let\oldnewlabel\newlabel
\let\contentsline\oldcontentsline
\let\newlabel\oldnewlabel
\providecommand\HyField@AuxAddToFields[1]{}
\providecommand\HyperFirstAtBeginDocument{\AtBeginDocument}
\select@language{english}
\setcounter{ContinuedFloat}{0}
\setcounter{ContinuedFloat}{0}
\setcounter{ContinuedFloat}{0}
\setcounter{ContinuedFloat}{0}
\setcounter{ContinuedFloat}{0}
\setcounter{ContinuedFloat}{0}
\setcounter{ContinuedFloat}{0}
\setcounter{Hfootnote}{0}
\setcounter{Hfootnote}{0}
\setcounter{Hfootnote}{0}
\setcounter{Hfootnote}{0}
\setcounter{Hfootnote}{0}
\setcounter{Hfootnote}{0}
\setcounter{Hfootnote}{0}
\setcounter{Item}{0}
\setcounter{Item}{0}
\setcounter{Item}{0}
\setcounter{Item}{0}
\setcounter{Item}{0}
\setcounter{Item}{0}
\setcounter{Item}{0}
\setcounter{LN@truepage}{17}
\setcounter{LN@truepage}{19}
\setcounter{LN@truepage}{21}
\setcounter{LN@truepage}{23}
\setcounter{LN@truepage}{25}
\setcounter{LN@truepage}{7}
\setcounter{LN@truepage}{9}
\setcounter{bookmark@seq@number}{12}
\setcounter{bookmark@seq@number}{15}
\setcounter{bookmark@seq@number}{18}
\setcounter{bookmark@seq@number}{1}
\setcounter{bookmark@seq@number}{1}
\setcounter{bookmark@seq@number}{4}
\setcounter{bookmark@seq@number}{8}
\setcounter{chapter}{0}
\setcounter{chapter}{0}
\setcounter{chapter}{0}
\setcounter{chapter}{1}
\setcounter{chapter}{2}
\setcounter{chapter}{3}
\setcounter{chapter}{4}
\setcounter{enumiii}{0}
\setcounter{enumiii}{0}
\setcounter{enumiii}{0}
\setcounter{enumiii}{0}
\setcounter{enumiii}{0}
\setcounter{enumiii}{0}
\setcounter{enumiii}{0}
\setcounter{enumii}{0}
\setcounter{enumii}{0}
\setcounter{enumii}{0}
\setcounter{enumii}{0}
\setcounter{enumii}{0}
\setcounter{enumii}{0}
\setcounter{enumii}{0}
\setcounter{enumiv}{0}
\setcounter{enumiv}{0}
\setcounter{enumiv}{0}
\setcounter{enumiv}{0}
\setcounter{enumiv}{0}
\setcounter{enumiv}{0}
\setcounter{enumiv}{0}
\setcounter{enumi}{0}
\setcounter{enumi}{0}
\setcounter{enumi}{0}
\setcounter{enumi}{0}
\setcounter{enumi}{0}
\setcounter{enumi}{0}
\setcounter{enumi}{0}
\setcounter{equation}{0}
\setcounter{equation}{0}
\setcounter{equation}{0}
\setcounter{equation}{0}
\setcounter{equation}{0}
\setcounter{equation}{0}
\setcounter{equation}{0}
\setcounter{figure}{0}
\setcounter{figure}{0}
\setcounter{figure}{0}
\setcounter{figure}{0}
\setcounter{figure}{0}
\setcounter{figure}{0}
\setcounter{figure}{0}
\setcounter{footnote}{0}
\setcounter{footnote}{0}
\setcounter{footnote}{0}
\setcounter{footnote}{0}
\setcounter{footnote}{0}
\setcounter{footnote}{0}
\setcounter{footnote}{0}
\setcounter{linenumber}{0}
\setcounter{linenumber}{0}
\setcounter{linenumber}{0}
\setcounter{linenumber}{0}
\setcounter{linenumber}{0}
\setcounter{linenumber}{0}
\setcounter{linenumber}{0}
\setcounter{lstlisting}{0}
\setcounter{lstlisting}{0}
\setcounter{lstlisting}{0}
\setcounter{lstlisting}{0}
\setcounter{lstlisting}{0}
\setcounter{lstlisting}{0}
\setcounter{lstlisting}{0}
\setcounter{lstnumber}{1}
\setcounter{lstnumber}{1}
\setcounter{lstnumber}{1}
\setcounter{lstnumber}{1}
\setcounter{lstnumber}{1}
\setcounter{lstnumber}{1}
\setcounter{lstnumber}{1}
\setcounter{mpfootnote}{0}
\setcounter{mpfootnote}{0}
\setcounter{mpfootnote}{0}
\setcounter{mpfootnote}{0}
\setcounter{mpfootnote}{0}
\setcounter{mpfootnote}{0}
\setcounter{mpfootnote}{0}
\setcounter{page}{14}
\setcounter{page}{2}
\setcounter{page}{4}
\setcounter{page}{4}
\setcounter{page}{6}
\setcounter{page}{6}
\setcounter{page}{8}
\setcounter{paragraph}{0}
\setcounter{paragraph}{0}
\setcounter{paragraph}{0}
\setcounter{paragraph}{0}
\setcounter{paragraph}{0}
\setcounter{paragraph}{0}
\setcounter{paragraph}{0}
\setcounter{part}{0}
\setcounter{part}{0}
\setcounter{part}{0}
\setcounter{part}{0}
\setcounter{part}{0}
\setcounter{part}{0}
\setcounter{part}{0}
\setcounter{section@level}{0}
\setcounter{section@level}{0}
\setcounter{section@level}{0}
\setcounter{section@level}{1}
\setcounter{section@level}{1}
\setcounter{section@level}{1}
\setcounter{section@level}{1}
\setcounter{section}{0}
\setcounter{section}{0}
\setcounter{section}{0}
\setcounter{section}{2}
\setcounter{section}{2}
\setcounter{section}{3}
\setcounter{section}{3}
\setcounter{subparagraph}{0}
\setcounter{subparagraph}{0}
\setcounter{subparagraph}{0}
\setcounter{subparagraph}{0}
\setcounter{subparagraph}{0}
\setcounter{subparagraph}{0}
\setcounter{subparagraph}{0}
\setcounter{subsection}{0}
\setcounter{subsection}{0}
\setcounter{subsection}{0}
\setcounter{subsection}{0}
\setcounter{subsection}{0}
\setcounter{subsection}{0}
\setcounter{subsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subsubsection}{0}
\setcounter{table}{0}
\setcounter{table}{0}
\setcounter{table}{0}
\setcounter{table}{0}
\setcounter{table}{0}
\setcounter{table}{0}
\setcounter{table}{0}
}
}
}
}
}
}
}
